# Generated by Django 4.0.5 on 2022-07-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compra',
            fields=[
                ('compra', models.IntegerField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=5050)),
                ('precio', models.CharField(max_length=30)),
                ('cantidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=30)),
                ('precio', models.CharField(max_length=30)),
            ],
        ),
    ]
