# Generated by Django 4.0.5 on 2022-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_alter_compra_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Producto',
            field=models.IntegerField(verbose_name='Id de Producto'),
        ),
    ]
