# Generated by Django 4.0.5 on 2022-07-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.IntegerField(verbose_name='Id de Descuento')),
                ('Descuento', models.CharField(max_length=30)),
                ('Porcentaje', models.CharField(max_length=30)),
            ],
        ),
    ]
