# Generated by Django 4.0.5 on 2022-07-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.IntegerField(max_length=50)),
                ('precio', models.CharField(max_length=30)),
                ('cantidad', models.CharField(max_length=30)),
            ],
        ),
    ]
